FROM ubuntu:18.04

#install required application and some handy tools
#note that python3 on ubuntu:18.04 is python3.6
RUN apt-get update && apt-get install -y \
	nano \
	net-tools \
	iputils-ping \
	python3 \
	python3-pip \
	python3-requests \
	tcpdump
