apiVersion: v1
kind: Service
metadata:
  name: app-humidity
  labels:
    app: app-humidity
spec:
  type: ClusterIP
  ports:
  - port: 7777
    protocol: UDP
  selector:
    app: app-humidity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-humidity
  name: app-humidity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-humidity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-humidity
    spec:
      containers:
      - image: sysc4907_group58/server
        name: app-humidity
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 7777
status: {}
